In [1]:
import pandas as pd

In [2]:
func_effects = pd.read_csv('293T_entry_func_effects.csv')
func_effects

         condition site wildtype mutant  effect
0     func_effects  100        G      A  -1.063
1     func_effects  100        G      C  -4.473
2     func_effects  100        G      D  -4.650
3     func_effects  100        G      E  -4.183
4     func_effects  100        G      F  -4.654
...            ...  ...      ...    ...     ...
9862  func_effects   99        P      S  -3.153
9863  func_effects   99        P      T  -2.867
9864  func_effects   99        P      V  -1.966
9865  func_effects   99        P      W  -4.663
9866  func_effects   99        P      Y  -4.227

[9867 rows x 5 columns]

In [3]:
map = pd.read_csv('site_numbering_map.csv')
map

     sequential_site reference_site sequential_wt region   rbs_region chain
0                  1             11             D    HA1  outside RBS     A
1                  2             12             K    HA1  outside RBS     A
2                  3             13             I    HA1  outside RBS     A
3                  4             14             C    HA1  outside RBS     A
4                  5             15             L    HA1  outside RBS     A
..               ...            ...           ...    ...          ...   ...
501              502            510             G    HA2  outside RBS   NaN
502              503            511             Y    HA2  outside RBS   NaN
503              504            512             K    HA2  outside RBS   NaN
504              505            513             D    HA2  outside RBS   NaN
505              506            514             V    HA2  outside RBS   NaN

[506 rows x 6 columns]

In [10]:
func_effects_ref = pd.merge(
    func_effects,
    map,
    left_on=['site'],
    right_on=['reference_site']
)[['condition', 'sequential_site', 'wildtype', 'mutant', 'effect', 'chain']].rename(
    columns={'sequential_site' : 'site'}
)

func_effects_ref.to_csv('293T_entry_func_effects_sequential.csv')